# currently a quarto project is required for metadata or brand extensions to work
project:
  type: default

brand:
  light: _extensions/brand/light-brand.yml
  dark: _extensions/brand/dark-brand.yml

format:
  html:
    theme:
      light: 
        - default
        - brand
      dark: 
        - default
        - brand
